all:
	@gcc zadanie.c -Wall -o zadanie1 -lpthread
	@gcc zadanie2.c -Wall -o zadanie2 -lpthread
	@gcc zadanie4.c -Wall -o zadanie4 -lpthread
	@gcc zadanieB.c -Wall -o zadanieB -lpthread
	@echo ''
	@echo 'Aby uruchomic program wpisz:'
	@echo './zadanie<X> <liczba watkow>'
	@echo ''

clean:
	@rm -f zadanie1 zadanie2 zadanie4 zadanieB
	@echo 'Successfully cleaned'