all:
	-s
	gcc program.c -Wall -o program
	@echo
	@echo '	Run program by typing ./program you may want add some directories'
	@echo
	mkdir testDir1
	mkdir testDir2
clean:
	rm -f program
	rmdir testDir1
	rmdir testDir2
	rm folders.txt
