all:
	@gcc wersja1.c -Wall -o wersja1 -lpthread
	@gcc wersja2.c -Wall -o wersja2 -lpthread
	@gcc wersja3.c -Wall -o wersja3 -lpthread
	@echo ''
	@echo 'Aby uruchomic program wpisz:'
	@echo './wersja<X> <liczba watkow> <szukane slowo> <liczba rekordow>'
	@echo 'gdzie X to wersja programu'
	@echo ''

clean:
	@rm -f wersja1 wersja2 wersja3
	@echo 'Successfully cleaned'